spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: KeycloakApplication
          uri: http://localhost:8181
          predicates:
            - Path=/users/**
        - id: KeycloakApplication
          uri: http://localhost:8181
          predicates:
            - Path=/groups/**
        - id: TaskApplication
          uri: http://localhost:8282
          predicates:
            - Path=/tasks/**
server:
  port : 8383